### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Dessix** [DSTech/MPM#6]
How should we license MPM? I, personally, am for permissive licensing such as the MIT license strategy, but we must consider compatibility with other licensing styles with which we must interoperate.

**Comment by clarkis117** [comment]
I generally agree with the MIT and BSD license strategies. As long as we don't have any libraries that are dependent on the GPLv2.

**Comment by Dessix** [comment]
We'll go with MIT and begin to phase out any licenses that are not compatible when possible.

**Comment by Dessix** [comment]
Added MIT license in c767e66db3e8cc2e5594978b5f701d668e655641.
