### ISSUE TITLE
Instances - Structuring

### ISSUE THREAD

**Issue by Dessix** [DSTech/MPM#9]
How should we structure instances?

We know that data about instances should be stored within their structure, probably in some `.mpm` folder or such, but data outside of instances should be handled in a stable way which can handle migrations to any formats we may require in the future. SQL handles much of this, but (Unlike other people) I am averse to writing huge schemas for a temporary implementation of a package format, and have put the SQLite-based datastore on hold until "necessary". I am tempted to set up a centralized DBreeze-based file within which non-instance data and repository caching can be stored.

Any ideas of how best to handle this data without loads of manual definitions and queries?

**Comment by clarkis117** [comment]
The data could be structured in an object and then outputted to a file in CLI-XML (or JSON) format.

**Comment by Dessix** [comment]
I may have just had an aneurysm at the suggestion of XML. We aren't Microsoft.

**Comment by Dessix** [comment]
Instance metadata is now stored as a subfolder of the instance, ".mpm", which contains simple SQLite-based string-to-string key-value stores which are, in the implementation, mapped to types using Json.Net to serialize both keys and values.

A central storage in the user's profile (also ".mpm") is used for storing non-instance metadata. The package cache is stored here, and this is also where information regarding package and hash repositories will also be located.

**Comment by Dessix** [comment]
Commenting but not reopening to mention that data storage will likely be changed to RaptorDB or its Key-Value predecessor for purposes of easier data management and more reliable ability to store arbitrary data. Performance is not as much of a concern here, and schema will likely change often enough to warrant this, but Raptor provides significantly more performance than the current adapter model which pretends SQLite is a kv-store.
